---
title: "Craft Beer Analysis"
author: "Ashwin Thota"
date: "June 30, 2017"
output:
  
  
  
  html_document:d
    keep_md: yes
---



```{r}
library(plyr)
beers <- read.csv("https://raw.githubusercontent.com/AshwinThotaDS/CaseStudy1/master/Data/Beers.csv",header=TRUE)
breweries<-read.csv("https://raw.githubusercontent.com/AshwinThotaDS/CaseStudy1/master/Data/Breweries.csv",header=TRUE)
head(breweries)
head(beers) 
```

##Question 1: How many breweries are present in each state?

```{r, fig.width=20,fig.height=5}
brew_count<-count(breweries,'State')
brew_count

ggplot(data = brew_count,aes(State, freq,fill=freq)) +geom_bar(color="black",stat = "identity")+theme(text=element_text(size=20))+  scale_fill_gradientn(
colours = terrain.colors(6)) 
```

Question 2:
Merge beer data with breweries data by brewery id. Print first 6 observations and the last six observations to check the merged file

```{r}
colnames(beers)
```
```{r}
colnames(breweries)
```
```{r}

colnames(breweries)[colnames(breweries)=="Brew_ID"]<-"Brewery_id"
colnames(breweries)
```

Merge the dat sets

```{r}
beer_brew<-merge(beers,breweries,by="Brewery_id")
head(beer_brew)
```
First 6 and Last 6

```{r}
head(beer_brew,6)
tail(beer_brew,6)
```

Question 3:
Report the number of NA's in each column.
```{r}
colSums(is.na(beer_brew))
```

Median of abv

```{r}
ABV_Median<-aggregate(ABV~State, beer_brew, median,na.action=na.omit)
IBU_median<-aggregate(IBU~State, beer_brew, median,na.action=na.omit)

```

```{r, fig.width=25,fig.height=8}

library(reshape2)
library(ggplot2)
ggplot(data = ABV_Median,aes(State, ABV,fill=ABV)) +geom_bar(color="black",stat = "identity")+theme(text=element_text(size=20))+ scale_fill_gradientn(
colours = heat.colors(6)) 
```
```{r, fig.width=25,fig.height=8}
ggplot(data = IBU_median,aes(State, IBU,fill=IBU)) +geom_bar(color="black",stat = "identity")+theme(text=element_text(size=20))+ scale_fill_gradientn(
colours = heat.colors(6)) 
```




Question 5
```{r}
beer_brew[which.max(beer_brew$ABV),]
beer_brew[which.max(beer_brew$IBU),]
```

```{r}
summary(beer_brew$ABV)
```
```{r}
ggplot(beer_brew, aes(beer_brew$ABV, beer_brew$IBU))+
  geom_point(shape=1) +
  geom_smooth(method = lm) 

lm.anv_ibu<-lm(beer_brew$ABV~ beer_brew$IBU)
summary(lm.anv_ibu)
lm(beer_brew$ABV~ beer_brew$IBU)

```

